// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GUIService is the entire Wails-to-FileES bridge.  It owns no domain state:
 * internal/gui/app reconstructs the authoritative presentation from IPC and
 * this service only publishes an immutable browser-friendly projection.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Reconnect is a presentation intent used by the offline screen.
 * @returns {$CancellablePromise<void>}
 */
export function Reconnect() {
    return $Call.ByID(4122126279);
}

/**
 * Refresh is a presentation intent: ask the shared IPC model to fetch a fresh
 * authoritative snapshot without tearing down its event subscription.
 * @returns {$CancellablePromise<void>}
 */
export function Refresh() {
    return $Call.ByID(2696308997);
}

/**
 * Snapshot returns what the IPC presentation model currently knows.  It never
 * reads the filesystem, repository metadata or server configuration itself.
 * @returns {$CancellablePromise<$models.Snapshot>}
 */
export function Snapshot() {
    return $Call.ByID(1886500514).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Snapshot.createFrom;
