// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class ActionAcceptance {
    /**
     * Creates a new ActionAcceptance instance.
     * @param {Partial<ActionAcceptance>} [$$source = {}] - The source object to create the ActionAcceptance.
     */
    constructor($$source = {}) {
        if (!("accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accepted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionAcceptance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionAcceptance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionAcceptance(/** @type {Partial<ActionAcceptance>} */($$parsedSource));
    }
}

export class ActionRequest {
    /**
     * Creates a new ActionRequest instance.
     * @param {Partial<ActionRequest>} [$$source = {}] - The source object to create the ActionRequest.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["repo_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["server_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reservation_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["notice_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["channel_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["channel_ids"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionRequest(/** @type {Partial<ActionRequest>} */($$parsedSource));
    }
}

export class ActivityProjection {
    /**
     * Creates a new ActivityProjection instance.
     * @param {Partial<ActivityProjection>} [$$source = {}] - The source object to create the ActivityProjection.
     */
    constructor($$source = {}) {
        if (!("repo_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo_id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["revision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["size"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivityProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActivityProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActivityProjection(/** @type {Partial<ActivityProjection>} */($$parsedSource));
    }
}

export class CycleProjection {
    /**
     * Creates a new CycleProjection instance.
     * @param {Partial<CycleProjection>} [$$source = {}] - The source object to create the CycleProjection.
     */
    constructor($$source = {}) {
        if (!("cycle_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cycle_id"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["phase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_tick_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["next_tick_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CycleProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CycleProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CycleProjection(/** @type {Partial<CycleProjection>} */($$parsedSource));
    }
}

export class ErrorProjection {
    /**
     * Creates a new ErrorProjection instance.
     * @param {Partial<ErrorProjection>} [$$source = {}] - The source object to create the ErrorProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["repo_id"] = undefined;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hint"] = undefined;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ErrorProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ErrorProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ErrorProjection(/** @type {Partial<ErrorProjection>} */($$parsedSource));
    }
}

export class JournalProjection {
    /**
     * Creates a new JournalProjection instance.
     * @param {Partial<JournalProjection>} [$$source = {}] - The source object to create the JournalProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("relative_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relative_time"] = "";
        }
        if (!("exact_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["exact_time"] = "";
        }
        if (!("repository" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repository"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["severity"] = undefined;
        }
        if (!("emphasized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["emphasized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JournalProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JournalProjection(/** @type {Partial<JournalProjection>} */($$parsedSource));
    }
}

export class DashboardPublicShareProjection {
    /**
     * Creates a new DashboardPublicShareProjection instance.
     * @param {Partial<DashboardPublicShareProjection>} [$$source = {}] - The source object to create the DashboardPublicShareProjection.
     */
    constructor($$source = {}) {
        for (const field of ["channel_id", "server_id", "repo_id", "repository", "address", "state"]) {
            if (!(field in $$source)) this[field] = "";
        }
        for (const field of ["source_root", "updated_at"]) {
            if (/** @type {any} */(false)) this[field] = undefined;
        }
        for (const field of ["recipient_count", "object_count"]) {
            if (!(field in $$source)) this[field] = 0;
        }
        for (const field of ["password_protected", "follow_head", "can_open", "can_revoke"]) {
            if (!(field in $$source)) this[field] = false;
        }
        Object.assign(this, $$source);
    }

    /**
     * @param {any} [$$source = {}]
     * @returns {DashboardPublicShareProjection}
     */
    static createFrom($$source = {}) {
        const $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DashboardPublicShareProjection(/** @type {Partial<DashboardPublicShareProjection>} */($$parsedSource));
    }
}

export class NoticeProjection {
    /**
     * Creates a new NoticeProjection instance.
     * @param {Partial<NoticeProjection>} [$$source = {}] - The source object to create the NoticeProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["repo_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["revision"] = undefined;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("acked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["acked"] = false;
        }
        if (!("can_ack" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_ack"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoticeProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NoticeProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NoticeProjection(/** @type {Partial<NoticeProjection>} */($$parsedSource));
    }
}

export class PairingAcceptance {
    /**
     * Creates a new PairingAcceptance instance.
     * @param {Partial<PairingAcceptance>} [$$source = {}] - The source object to create the PairingAcceptance.
     */
    constructor($$source = {}) {
        if (!("accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accepted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairingAcceptance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PairingAcceptance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PairingAcceptance(/** @type {Partial<PairingAcceptance>} */($$parsedSource));
    }
}

export class PairingClose {
    /**
     * Creates a new PairingClose instance.
     * @param {Partial<PairingClose>} [$$source = {}] - The source object to create the PairingClose.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairingClose instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PairingClose}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PairingClose(/** @type {Partial<PairingClose>} */($$parsedSource));
    }
}

export class PairingSnapshot {
    /**
     * Creates a new PairingSnapshot instance.
     * @param {Partial<PairingSnapshot>} [$$source = {}] - The source object to create the PairingSnapshot.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["qr_data_url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["expires_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["display_until"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairingSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PairingSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PairingSnapshot(/** @type {Partial<PairingSnapshot>} */($$parsedSource));
    }
}

export class PendingActionProjection {
    /**
     * Creates a new PendingActionProjection instance.
     * @param {Partial<PendingActionProjection>} [$$source = {}] - The source object to create the PendingActionProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["repo_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["server_id"] = undefined;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["started_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingActionProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PendingActionProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PendingActionProjection(/** @type {Partial<PendingActionProjection>} */($$parsedSource));
    }
}

export class PromptAcceptance {
    /**
     * Creates a new PromptAcceptance instance.
     * @param {Partial<PromptAcceptance>} [$$source = {}] - The source object to create the PromptAcceptance.
     */
    constructor($$source = {}) {
        if (!("accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accepted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptAcceptance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromptAcceptance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptAcceptance(/** @type {Partial<PromptAcceptance>} */($$parsedSource));
    }
}

export class PromptChoice {
    /**
     * Creates a new PromptChoice instance.
     * @param {Partial<PromptChoice>} [$$source = {}] - The source object to create the PromptChoice.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("confirmed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["value"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptChoice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromptChoice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptChoice(/** @type {Partial<PromptChoice>} */($$parsedSource));
    }
}

export class PromptOption {
    /**
     * Creates a new PromptOption instance.
     * @param {Partial<PromptOption>} [$$source = {}] - The source object to create the PromptOption.
     */
    constructor($$source = {}) {
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["detail"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromptOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptOption(/** @type {Partial<PromptOption>} */($$parsedSource));
    }
}

export class PromptSnapshot {
    /**
     * Creates a new PromptSnapshot instance.
     * @param {Partial<PromptSnapshot>} [$$source = {}] - The source object to create the PromptSnapshot.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["label"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PromptOption[] | undefined}
             */
            this["options"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["default"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["placeholder"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["secret"] = undefined;
        }
        if (!("confirm_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["confirm_text"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cancel_text"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromptSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new PromptSnapshot(/** @type {Partial<PromptSnapshot>} */($$parsedSource));
    }
}

export class PublicShareProjection {
    /**
     * Creates a new PublicShareProjection instance.
     * @param {Partial<PublicShareProjection>} [$$source = {}] - The source object to create the PublicShareProjection.
     */
    constructor($$source = {}) {
        if (!("channel_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["channel_id"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("source_root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_root"] = "";
        }
        if (!("recipients" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["recipients"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["revision"] = "";
        }
        if (!("can_edit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_edit"] = false;
        }
        if (!("can_revoke" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_revoke"] = false;
        }
        if (!("can_delete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_delete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicShareProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicShareProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicShareProjection(/** @type {Partial<PublicShareProjection>} */($$parsedSource));
    }
}

export class QuarantineItemProjection {
    /**
     * Creates a new QuarantineItemProjection instance.
     * @param {Partial<QuarantineItemProjection>} [$$source = {}] - The source object to create the QuarantineItemProjection.
     */
    constructor($$source = {}) {
        if (!("upload_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["upload_id"] = "";
        }
        if (!("original_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["original_name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("size_label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["size_label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["av_verdict"] = undefined;
        }
        if (!("remaining_hours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remaining_hours"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuarantineItemProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuarantineItemProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuarantineItemProjection(/** @type {Partial<QuarantineItemProjection>} */($$parsedSource));
    }
}

export class RealmGrantProjection {
    /**
     * Creates a new RealmGrantProjection instance.
     * @param {Partial<RealmGrantProjection>} [$$source = {}] - The source object to create the RealmGrantProjection.
     */
    constructor($$source = {}) {
        if (!("realm_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["realm_id"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("access" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["access"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("can_read" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_read"] = false;
        }
        if (!("can_write" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_write"] = false;
        }
        if (!("can_revoke" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_revoke"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RealmGrantProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RealmGrantProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RealmGrantProjection(/** @type {Partial<RealmGrantProjection>} */($$parsedSource));
    }
}

export class RepoProjection {
    /**
     * Creates a new RepoProjection instance.
     * @param {Partial<RepoProjection>} [$$source = {}] - The source object to create the RepoProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("server_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_id"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["local_path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (!("attached" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["attached"] = false;
        }
        if (!("access" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["access"] = "";
        }
        if (!("ownership" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ownership"] = "";
        }
        if (!("attachment_policy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["attachment_policy"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("display_state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_state"] = "";
        }
        if (!("connectivity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectivity"] = "";
        }
        if (!("local_revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["local_revision"] = 0;
        }
        if (!("head_revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["head_revision"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["working_copy_bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["working_copy_size_known"] = undefined;
        }
        if (!("pending_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending_files"] = 0;
        }
        if (!("pending_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending_bytes"] = 0;
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflicts"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["current_operation"] = undefined;
        }
        if (!("reservation_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reservation_count"] = 0;
        }
        if (!("can_open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_open"] = false;
        }
        if (!("can_lock" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_lock"] = false;
        }
        if (!("can_unlock" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_unlock"] = false;
        }
        if (!("can_publish" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_publish"] = false;
        }
        if (!("can_review_quarantine" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_review_quarantine"] = false;
        }
        if (!("cycle" in $$source)) {
            /**
             * @member
             * @type {CycleProjection}
             */
            this["cycle"] = (new CycleProjection());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["server_deleted"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["local_cleanup_pending"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["retain_until"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["recovery_operation_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["recovery_available"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["recovery_pending"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cleanup_error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["purpose"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoProjection}
     */
    static createFrom($$source = {}) {
        const $$createField25_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cycle" in $$parsedSource) {
            $$parsedSource["cycle"] = $$createField25_0($$parsedSource["cycle"]);
        }
        return new RepoProjection(/** @type {Partial<RepoProjection>} */($$parsedSource));
    }
}

export class RepositoryAcceptance {
    /**
     * Creates a new RepositoryAcceptance instance.
     * @param {Partial<RepositoryAcceptance>} [$$source = {}] - The source object to create the RepositoryAcceptance.
     */
    constructor($$source = {}) {
        if (!("accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accepted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepositoryAcceptance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepositoryAcceptance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepositoryAcceptance(/** @type {Partial<RepositoryAcceptance>} */($$parsedSource));
    }
}

export class RepositoryActionProjection {
    /**
     * Creates a new RepositoryActionProjection instance.
     * @param {Partial<RepositoryActionProjection>} [$$source = {}] - The source object to create the RepositoryActionProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("tone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepositoryActionProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepositoryActionProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepositoryActionProjection(/** @type {Partial<RepositoryActionProjection>} */($$parsedSource));
    }
}

export class RepositoryChoice {
    /**
     * Creates a new RepositoryChoice instance.
     * @param {Partial<RepositoryChoice>} [$$source = {}] - The source object to create the RepositoryChoice.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("server_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_id"] = "";
        }
        if (!("repo_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["channel_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["realm_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["upload_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepositoryChoice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepositoryChoice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepositoryChoice(/** @type {Partial<RepositoryChoice>} */($$parsedSource));
    }
}

export class RepositoryContextProjection {
    /**
     * Creates a new RepositoryContextProjection instance.
     * @param {Partial<RepositoryContextProjection>} [$$source = {}] - The source object to create the RepositoryContextProjection.
     */
    constructor($$source = {}) {
        if (!("server_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_id"] = "";
        }
        if (!("server_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_name"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("realm" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["realm"] = "";
        }
        if (!("repo_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("local_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["local_path"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("access" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["access"] = "";
        }
        if (!("editing" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["editing"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepositoryContextProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepositoryContextProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepositoryContextProjection(/** @type {Partial<RepositoryContextProjection>} */($$parsedSource));
    }
}

export class RepositorySnapshot {
    /**
     * Creates a new RepositorySnapshot instance.
     * @param {Partial<RepositorySnapshot>} [$$source = {}] - The source object to create the RepositorySnapshot.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("busy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["busy"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["focus_channel_id"] = undefined;
        }
        if (!("context" in $$source)) {
            /**
             * @member
             * @type {RepositoryContextProjection}
             */
            this["context"] = (new RepositoryContextProjection());
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {RepositoryActionProjection[]}
             */
            this["actions"] = [];
        }
        if (!("shares" in $$source)) {
            /**
             * @member
             * @type {PublicShareProjection[]}
             */
            this["shares"] = [];
        }
        if (!("grants" in $$source)) {
            /**
             * @member
             * @type {RealmGrantProjection[]}
             */
            this["grants"] = [];
        }
        if (!("uploads" in $$source)) {
            /**
             * @member
             * @type {UploadChannelProjection[]}
             */
            this["uploads"] = [];
        }
        if (!("quarantine" in $$source)) {
            /**
             * @member
             * @type {QuarantineItemProjection[]}
             */
            this["quarantine"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepositorySnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepositorySnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType9;
        const $$createField9_0 = $$createType11;
        const $$createField10_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField5_0($$parsedSource["context"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField6_0($$parsedSource["actions"]);
        }
        if ("shares" in $$parsedSource) {
            $$parsedSource["shares"] = $$createField7_0($$parsedSource["shares"]);
        }
        if ("grants" in $$parsedSource) {
            $$parsedSource["grants"] = $$createField8_0($$parsedSource["grants"]);
        }
        if ("uploads" in $$parsedSource) {
            $$parsedSource["uploads"] = $$createField9_0($$parsedSource["uploads"]);
        }
        if ("quarantine" in $$parsedSource) {
            $$parsedSource["quarantine"] = $$createField10_0($$parsedSource["quarantine"]);
        }
        return new RepositorySnapshot(/** @type {Partial<RepositorySnapshot>} */($$parsedSource));
    }
}

export class ReservationProjection {
    /**
     * Creates a new ReservationProjection instance.
     * @param {Partial<ReservationProjection>} [$$source = {}] - The source object to create the ReservationProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("server_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_id"] = "";
        }
        if (!("repo_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo_id"] = "";
        }
        if (!("repository" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repository"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["owner_label"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["created_at"] = undefined;
        }
        if (!("can_release" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_release"] = false;
        }
        if (!("local_changes" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["local_changes"] = false;
        }
        if (!("active_passport" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active_passport"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReservationProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReservationProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReservationProjection(/** @type {Partial<ReservationProjection>} */($$parsedSource));
    }
}

export class ServerProjection {
    /**
     * Creates a new ServerProjection instance.
     * @param {Partial<ServerProjection>} [$$source = {}] - The source object to create the ServerProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("client_role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_role"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["realm_alias"] = undefined;
        }
        if (!("repository_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["repository_count"] = 0;
        }
        if (!("repositories_ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["repositories_ready"] = false;
        }
        if (!("pending_required_repos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending_required_repos"] = 0;
        }
        if (!("reservation_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reservation_count"] = 0;
        }
        if (!("reservations_known" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reservations_known"] = false;
        }
        if (!("session_timeout_minutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session_timeout_minutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerProjection(/** @type {Partial<ServerProjection>} */($$parsedSource));
    }
}

export class SettingsAcceptance {
    /**
     * Creates a new SettingsAcceptance instance.
     * @param {Partial<SettingsAcceptance>} [$$source = {}] - The source object to create the SettingsAcceptance.
     */
    constructor($$source = {}) {
        if (!("accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accepted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsAcceptance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsAcceptance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsAcceptance(/** @type {Partial<SettingsAcceptance>} */($$parsedSource));
    }
}

export class SettingsActionProjection {
    /**
     * Creates a new SettingsActionProjection instance.
     * @param {Partial<SettingsActionProjection>} [$$source = {}] - The source object to create the SettingsActionProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("tone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsActionProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsActionProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsActionProjection(/** @type {Partial<SettingsActionProjection>} */($$parsedSource));
    }
}

export class SettingsChoice {
    /**
     * Creates a new SettingsChoice instance.
     * @param {Partial<SettingsChoice>} [$$source = {}] - The source object to create the SettingsChoice.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("server_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsChoice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsChoice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsChoice(/** @type {Partial<SettingsChoice>} */($$parsedSource));
    }
}

export class SettingsServerProjection {
    /**
     * Creates a new SettingsServerProjection instance.
     * @param {Partial<SettingsServerProjection>} [$$source = {}] - The source object to create the SettingsServerProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("realm" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["realm"] = "";
        }
        if (!("client_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_id"] = "";
        }
        if (!("session_timeout_min" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session_timeout_min"] = 0;
        }
        if (!("can_set_session_timeout" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_set_session_timeout"] = false;
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {SettingsActionProjection[]}
             */
            this["actions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsServerProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsServerProjection}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField7_0($$parsedSource["actions"]);
        }
        return new SettingsServerProjection(/** @type {Partial<SettingsServerProjection>} */($$parsedSource));
    }
}

export class SettingsSnapshot {
    /**
     * Creates a new SettingsSnapshot instance.
     * @param {Partial<SettingsSnapshot>} [$$source = {}] - The source object to create the SettingsSnapshot.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {SettingsServerProjection}
             */
            this["server"] = (new SettingsServerProjection());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("server" in $$parsedSource) {
            $$parsedSource["server"] = $$createField3_0($$parsedSource["server"]);
        }
        return new SettingsSnapshot(/** @type {Partial<SettingsSnapshot>} */($$parsedSource));
    }
}

export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("stale" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["stale"] = false;
        }
        if (!("daemon_state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["daemon_state"] = "";
        }
        if (!("uptime_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uptime_sec"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_refresh"] = undefined;
        }
        if (!("icon_state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon_state"] = "";
        }
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["capabilities"] = [];
        }
        if (!("servers" in $$source)) {
            /**
             * @member
             * @type {ServerProjection[]}
             */
            this["servers"] = [];
        }
        if (!("repositories" in $$source)) {
            /**
             * @member
             * @type {RepoProjection[]}
             */
            this["repositories"] = [];
        }
        if (!("reservations" in $$source)) {
            /**
             * @member
             * @type {ReservationProjection[]}
             */
            this["reservations"] = [];
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {ErrorProjection[]}
             */
            this["errors"] = [];
        }
        if (!("activity" in $$source)) {
            /**
             * @member
             * @type {ActivityProjection[]}
             */
            this["activity"] = [];
        }
        if (!("journal" in $$source)) {
            /**
             * @member
             * @type {JournalProjection[]}
             */
            this["journal"] = [];
        }
        if (!("pending_actions" in $$source)) {
            /**
             * @member
             * @type {PendingActionProjection[]}
             */
            this["pending_actions"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["next_cycle_at"] = undefined;
        }
        if (!("cycle_running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cycle_running"] = false;
        }
        if (!("notices" in $$source)) {
            /**
             * @member
             * @type {NoticeProjection[]}
             */
            this["notices"] = [];
        }
        if (!("public_shares" in $$source)) {
            /**
             * @member
             * @type {DashboardPublicShareProjection[]}
             */
            this["public_shares"] = [];
        }
        if (!("public_shares_known" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["public_shares_known"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {UpdateProjection | null | undefined}
             */
            this["update"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType17;
        const $$createField8_0 = $$createType19;
        const $$createField9_0 = $$createType21;
        const $$createField10_0 = $$createType23;
        const $$createField11_0 = $$createType25;
        const $$createField12_0 = $$createType27;
        const $$createField13_0 = $$createType29;
        const $$createField14_0 = $$createType31;
        const $$createField17_0 = $$createType33;
        const $$createField18_0 = $$createType35;
        const $$createField19_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField7_0($$parsedSource["capabilities"]);
        }
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField8_0($$parsedSource["servers"]);
        }
        if ("repositories" in $$parsedSource) {
            $$parsedSource["repositories"] = $$createField9_0($$parsedSource["repositories"]);
        }
        if ("reservations" in $$parsedSource) {
            $$parsedSource["reservations"] = $$createField10_0($$parsedSource["reservations"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField11_0($$parsedSource["errors"]);
        }
        if ("activity" in $$parsedSource) {
            $$parsedSource["activity"] = $$createField12_0($$parsedSource["activity"]);
        }
        if ("journal" in $$parsedSource) {
            $$parsedSource["journal"] = $$createField13_0($$parsedSource["journal"]);
        }
        if ("pending_actions" in $$parsedSource) {
            $$parsedSource["pending_actions"] = $$createField14_0($$parsedSource["pending_actions"]);
        }
        if ("notices" in $$parsedSource) {
            $$parsedSource["notices"] = $$createField17_0($$parsedSource["notices"]);
        }
        if ("public_shares" in $$parsedSource) {
            $$parsedSource["public_shares"] = $$createField18_0($$parsedSource["public_shares"]);
        }
        if ("update" in $$parsedSource) {
            $$parsedSource["update"] = $$createField19_0($$parsedSource["update"]);
        }
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

export class UpdateProjection {
    /**
     * Creates a new UpdateProjection instance.
     * @param {Partial<UpdateProjection>} [$$source = {}] - The source object to create the UpdateProjection.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["available_version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["summary"] = undefined;
        }
        if (!("restart_required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restart_required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateProjection(/** @type {Partial<UpdateProjection>} */($$parsedSource));
    }
}

export class UploadChannelProjection {
    /**
     * Creates a new UploadChannelProjection instance.
     * @param {Partial<UploadChannelProjection>} [$$source = {}] - The source object to create the UploadChannelProjection.
     */
    constructor($$source = {}) {
        if (!("channel_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["channel_id"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("recipients" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["recipients"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["require_otp"] = undefined;
        }
        if (!("can_edit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_edit"] = false;
        }
        if (!("can_revoke" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_revoke"] = false;
        }
        if (!("can_delete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_delete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadChannelProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UploadChannelProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadChannelProjection(/** @type {Partial<UploadChannelProjection>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PromptOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = CycleProjection.createFrom;
const $$createType3 = RepositoryContextProjection.createFrom;
const $$createType4 = RepositoryActionProjection.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = PublicShareProjection.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = RealmGrantProjection.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = UploadChannelProjection.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = QuarantineItemProjection.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = SettingsActionProjection.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = SettingsServerProjection.createFrom;
const $$createType17 = $Create.Array($Create.Any);
const $$createType18 = ServerProjection.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = RepoProjection.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = ReservationProjection.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = ErrorProjection.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = ActivityProjection.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = JournalProjection.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = PendingActionProjection.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = NoticeProjection.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = DashboardPublicShareProjection.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = UpdateProjection.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
