// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class ActionAcceptance {
    /**
     * Creates a new ActionAcceptance instance.
     * @param {Partial<ActionAcceptance>} [$$source = {}] - The source object to create the ActionAcceptance.
     */
    constructor($$source = {}) {
        if (!("accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["accepted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["code"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionAcceptance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionAcceptance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionAcceptance(/** @type {Partial<ActionAcceptance>} */($$parsedSource));
    }
}

export class ActionRequest {
    /**
     * Creates a new ActionRequest instance.
     * @param {Partial<ActionRequest>} [$$source = {}] - The source object to create the ActionRequest.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["repo_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reservation_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionRequest(/** @type {Partial<ActionRequest>} */($$parsedSource));
    }
}

export class ActivityProjection {
    /**
     * Creates a new ActivityProjection instance.
     * @param {Partial<ActivityProjection>} [$$source = {}] - The source object to create the ActivityProjection.
     */
    constructor($$source = {}) {
        if (!("repo_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo_id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["revision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivityProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActivityProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActivityProjection(/** @type {Partial<ActivityProjection>} */($$parsedSource));
    }
}

export class ErrorProjection {
    /**
     * Creates a new ErrorProjection instance.
     * @param {Partial<ErrorProjection>} [$$source = {}] - The source object to create the ErrorProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["repo_id"] = undefined;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hint"] = undefined;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ErrorProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ErrorProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ErrorProjection(/** @type {Partial<ErrorProjection>} */($$parsedSource));
    }
}

export class JournalProjection {
    /**
     * Creates a new JournalProjection instance.
     * @param {Partial<JournalProjection>} [$$source = {}] - The source object to create the JournalProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("relative_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relative_time"] = "";
        }
        if (!("exact_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["exact_time"] = "";
        }
        if (!("repository" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repository"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["severity"] = undefined;
        }
        if (!("emphasized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["emphasized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JournalProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JournalProjection(/** @type {Partial<JournalProjection>} */($$parsedSource));
    }
}

export class NoticeProjection {
    /**
     * Creates a new NoticeProjection instance.
     * @param {Partial<NoticeProjection>} [$$source = {}] - The source object to create the NoticeProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["repo_id"] = undefined;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoticeProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NoticeProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NoticeProjection(/** @type {Partial<NoticeProjection>} */($$parsedSource));
    }
}

export class RepoProjection {
    /**
     * Creates a new RepoProjection instance.
     * @param {Partial<RepoProjection>} [$$source = {}] - The source object to create the RepoProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("server_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_id"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["local_path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (!("attached" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["attached"] = false;
        }
        if (!("access" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["access"] = "";
        }
        if (!("ownership" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ownership"] = "";
        }
        if (!("attachment_policy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["attachment_policy"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("display_state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_state"] = "";
        }
        if (!("connectivity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectivity"] = "";
        }
        if (!("local_revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["local_revision"] = 0;
        }
        if (!("head_revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["head_revision"] = 0;
        }
        if (!("pending_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending_files"] = 0;
        }
        if (!("pending_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending_bytes"] = 0;
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflicts"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["current_operation"] = undefined;
        }
        if (!("reservation_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reservation_count"] = 0;
        }
        if (!("can_open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_open"] = false;
        }
        if (!("can_lock" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_lock"] = false;
        }
        if (!("can_unlock" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_unlock"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepoProjection(/** @type {Partial<RepoProjection>} */($$parsedSource));
    }
}

export class ReservationProjection {
    /**
     * Creates a new ReservationProjection instance.
     * @param {Partial<ReservationProjection>} [$$source = {}] - The source object to create the ReservationProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("server_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server_id"] = "";
        }
        if (!("repo_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo_id"] = "";
        }
        if (!("repository" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repository"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["owner_label"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["created_at"] = undefined;
        }
        if (!("can_release" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["can_release"] = false;
        }
        if (!("local_changes" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["local_changes"] = false;
        }
        if (!("active_passport" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active_passport"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReservationProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReservationProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReservationProjection(/** @type {Partial<ReservationProjection>} */($$parsedSource));
    }
}

export class ServerProjection {
    /**
     * Creates a new ServerProjection instance.
     * @param {Partial<ServerProjection>} [$$source = {}] - The source object to create the ServerProjection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("client_role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_role"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["realm_alias"] = undefined;
        }
        if (!("repository_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["repository_count"] = 0;
        }
        if (!("repositories_ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["repositories_ready"] = false;
        }
        if (!("pending_required_repos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending_required_repos"] = 0;
        }
        if (!("reservation_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reservation_count"] = 0;
        }
        if (!("reservations_known" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reservations_known"] = false;
        }
        if (!("session_timeout_minutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["session_timeout_minutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerProjection(/** @type {Partial<ServerProjection>} */($$parsedSource));
    }
}

export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("stale" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["stale"] = false;
        }
        if (!("daemon_state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["daemon_state"] = "";
        }
        if (!("uptime_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uptime_sec"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_refresh"] = undefined;
        }
        if (!("icon_state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon_state"] = "";
        }
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["capabilities"] = [];
        }
        if (!("servers" in $$source)) {
            /**
             * @member
             * @type {ServerProjection[]}
             */
            this["servers"] = [];
        }
        if (!("repositories" in $$source)) {
            /**
             * @member
             * @type {RepoProjection[]}
             */
            this["repositories"] = [];
        }
        if (!("reservations" in $$source)) {
            /**
             * @member
             * @type {ReservationProjection[]}
             */
            this["reservations"] = [];
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {ErrorProjection[]}
             */
            this["errors"] = [];
        }
        if (!("activity" in $$source)) {
            /**
             * @member
             * @type {ActivityProjection[]}
             */
            this["activity"] = [];
        }
        if (!("journal" in $$source)) {
            /**
             * @member
             * @type {JournalProjection[]}
             */
            this["journal"] = [];
        }
        if (!("notices" in $$source)) {
            /**
             * @member
             * @type {NoticeProjection[]}
             */
            this["notices"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {UpdateProjection | null | undefined}
             */
            this["update"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType4;
        const $$createField10_0 = $$createType6;
        const $$createField11_0 = $$createType8;
        const $$createField12_0 = $$createType10;
        const $$createField13_0 = $$createType12;
        const $$createField14_0 = $$createType14;
        const $$createField15_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField7_0($$parsedSource["capabilities"]);
        }
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField8_0($$parsedSource["servers"]);
        }
        if ("repositories" in $$parsedSource) {
            $$parsedSource["repositories"] = $$createField9_0($$parsedSource["repositories"]);
        }
        if ("reservations" in $$parsedSource) {
            $$parsedSource["reservations"] = $$createField10_0($$parsedSource["reservations"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField11_0($$parsedSource["errors"]);
        }
        if ("activity" in $$parsedSource) {
            $$parsedSource["activity"] = $$createField12_0($$parsedSource["activity"]);
        }
        if ("journal" in $$parsedSource) {
            $$parsedSource["journal"] = $$createField13_0($$parsedSource["journal"]);
        }
        if ("notices" in $$parsedSource) {
            $$parsedSource["notices"] = $$createField14_0($$parsedSource["notices"]);
        }
        if ("update" in $$parsedSource) {
            $$parsedSource["update"] = $$createField15_0($$parsedSource["update"]);
        }
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

export class UpdateProjection {
    /**
     * Creates a new UpdateProjection instance.
     * @param {Partial<UpdateProjection>} [$$source = {}] - The source object to create the UpdateProjection.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["available_version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["summary"] = undefined;
        }
        if (!("restart_required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restart_required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateProjection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateProjection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateProjection(/** @type {Partial<UpdateProjection>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ServerProjection.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = RepoProjection.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ReservationProjection.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ErrorProjection.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ActivityProjection.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = JournalProjection.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = NoticeProjection.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = UpdateProjection.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
