// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RepositoryService owns the presentation session for one repository window.
 * It receives already-authorised models from the shared controller and returns
 * only opaque IDs plus closed action enums. It never calls daemon IPC.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel closes only the repository presentation session.
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(2468657995);
}

/**
 * ChooseAction returns one action from the current repository projection.
 * @param {$models.RepositoryChoice} choice
 * @returns {$CancellablePromise<$models.RepositoryAcceptance>}
 */
export function ChooseAction(choice) {
    return $Call.ByID(3219507274, choice).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ChooseGrant returns an action only for a recipient projected by the current
 * grant directory. Realm identifiers stay opaque and are never accepted from
 * an older or foreign repository session.
 * @param {$models.RepositoryChoice} choice
 * @returns {$CancellablePromise<$models.RepositoryAcceptance>}
 */
export function ChooseGrant(choice) {
    return $Call.ByID(1416988886, choice).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ChooseShare returns an action only for a channel present in the current
 * authoritative list. Create is the sole channel-less operation.
 * @param {$models.RepositoryChoice} choice
 * @returns {$CancellablePromise<$models.RepositoryAcceptance>}
 */
export function ChooseShare(choice) {
    return $Call.ByID(1684290107, choice).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ChooseUpload returns an action only for a shelf present in the current
 * authoritative channel list. Create is the sole channel-less operation.
 * @param {$models.RepositoryChoice} choice
 * @returns {$CancellablePromise<$models.RepositoryAcceptance>}
 */
export function ChooseUpload(choice) {
    return $Call.ByID(1155137217, choice).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RepositorySnapshot>}
 */
export function Snapshot() {
    return $Call.ByID(2799497533).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.RepositoryAcceptance.createFrom;
const $$createType1 = $models.RepositorySnapshot.createFrom;
