// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the browser-facing half of the Wails settings window.
 * It only projects choices already authorised by the shared action model and
 * returns opaque IDs to the controller. It never calls daemon IPC itself.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel closes only the presentation session. It cannot stop FileES or
 * mutate server state.
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(1433299486);
}

/**
 * Choose accepts only actions exposed by the current server-scoped model.
 * Acceptance means the choice reached the shared controller, not that the
 * subsequent daemon mutation succeeded.
 * @param {$models.SettingsChoice} choice
 * @returns {$CancellablePromise<$models.SettingsAcceptance>}
 */
export function Choose(choice) {
    return $Call.ByID(2673445037, choice).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Snapshot returns the last immutable settings projection. A hidden window
 * may call it while loading; Revision zero means there is no active context.
 * @returns {$CancellablePromise<$models.SettingsSnapshot>}
 */
export function Snapshot() {
    return $Call.ByID(4236852856).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SettingsAcceptance.createFrom;
const $$createType1 = $models.SettingsSnapshot.createFrom;
