package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"filees/internal/releaseenvelope"
)

func stageBundle(t *testing.T, dir, name, body string) string {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	full := filepath.Join(dir, name)
	if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return full
}

func TestBothDocumentsAreWrittenAndWouldBeAccepted(t *testing.T) {
	root := t.TempDir()
	releaseRoot := filepath.Join(root, "releases", "r819", "windows-amd64")
	bundle := stageBundle(t, releaseRoot, "filees-client-windows-amd64.tar.gz", "pretend bundle")
	channel := filepath.Join(root, "releases", "r819", "channel.v2.json")

	if err := run(bundle, "desktop-client", "windows-amd64", "r819", "0.1.15.819", "alpha-key", "",
		releaseRoot, channel, "", 819, 1); err != nil {
		t.Fatalf("run: %v", err)
	}

	manifestRaw, err := os.ReadFile(filepath.Join(releaseRoot, "manifest.json"))
	if err != nil {
		t.Fatal(err)
	}
	// Read back through the client's own parser, because that is the only
	// reader whose opinion matters.
	manifest, err := releaseenvelope.ParseArtifactManifest(manifestRaw)
	if err != nil {
		t.Fatalf("the client would refuse the manifest: %v", err)
	}
	if len(manifest.Artifacts) != 1 || manifest.Artifacts[0].Source != "filees-client-windows-amd64.tar.gz" {
		t.Fatalf("artifacts = %+v", manifest.Artifacts)
	}
	if manifest.Artifacts[0].Size != int64(len("pretend bundle")) {
		t.Errorf("size = %d, want %d", manifest.Artifacts[0].Size, len("pretend bundle"))
	}

	envelopeRaw, err := os.ReadFile(channel)
	if err != nil {
		t.Fatal(err)
	}
	envelope, err := releaseenvelope.ParseEnvelope(envelopeRaw, time.Now())
	if err != nil {
		t.Fatalf("the client would refuse the envelope: %v", err)
	}
	if len(envelope.Components) != 1 || envelope.Components[0].Manifest != "releases/r819/windows-amd64/manifest.json" {
		t.Fatalf("components = %+v", envelope.Components)
	}
	// The two must agree on every field the resolver cross-checks, which is the
	// reason they are generated by one command.
	if envelope.ReleaseID != manifest.ReleaseID || envelope.Sequence != manifest.Sequence ||
		envelope.SecurityEpoch != manifest.SecurityEpoch || envelope.KeyID != manifest.KeyID {
		t.Error("the envelope and the manifest disagree on the release they describe")
	}
}

// Publishing one platform must not drop the others.
//
// The envelope covers a whole channel, so regenerating it from a single build
// would remove every platform not in that build - a Windows release that stops
// Linux clients updating, discovered by a Linux user long afterwards.
func TestPublishingOnePlatformKeepsTheOthers(t *testing.T) {
	root := t.TempDir()
	existing := filepath.Join(root, "previous.v2.json")
	previous := releaseenvelope.Envelope{
		SchemaVersion: releaseenvelope.SchemaVersion, ReleaseID: "r800", Sequence: 800, SecurityEpoch: 1,
		KeyID: "alpha-key", ExpiresAt: time.Now().AddDate(1, 0, 0).UTC().Format(time.RFC3339),
		Components: []releaseenvelope.Component{
			{Name: "desktop-client", Platform: "linux-amd64", Manifest: "releases/r800/linux-amd64/manifest.json"},
		},
	}
	encoded, err := json.MarshalIndent(previous, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(existing, encoded, 0o644); err != nil {
		t.Fatal(err)
	}

	releaseRoot := filepath.Join(root, "releases", "r819", "windows-amd64")
	bundle := stageBundle(t, releaseRoot, "filees-client-windows-amd64.tar.gz", "pretend bundle")
	channel := filepath.Join(root, "releases", "r819", "channel.v2.json")
	if err := run(bundle, "desktop-client", "windows-amd64", "r819", "0.1.15.819", "alpha-key", "",
		releaseRoot, channel, existing, 819, 1); err != nil {
		t.Fatalf("run: %v", err)
	}
	raw, err := os.ReadFile(channel)
	if err != nil {
		t.Fatal(err)
	}
	envelope, err := releaseenvelope.ParseEnvelope(raw, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	platforms := make([]string, 0, len(envelope.Components))
	for _, component := range envelope.Components {
		platforms = append(platforms, component.Platform)
	}
	if len(platforms) != 2 {
		t.Fatalf("platforms = %v, want linux-amd64 kept beside windows-amd64", platforms)
	}
	// And the linux entry still points at the release it was published from,
	// not at this one.
	for _, component := range envelope.Components {
		if component.Platform == "linux-amd64" && component.Manifest != "releases/r800/linux-amd64/manifest.json" {
			t.Errorf("the linux component was repointed at this release: %s", component.Manifest)
		}
	}
}

// A release is immutable. A rebuild that quietly replaced a signed one is how
// two different binaries end up sharing an identifier.
func TestAnExistingReleaseIsNeverOverwritten(t *testing.T) {
	root := t.TempDir()
	releaseRoot := filepath.Join(root, "releases", "r819", "windows-amd64")
	bundle := stageBundle(t, releaseRoot, "filees-client-windows-amd64.tar.gz", "pretend bundle")
	channel := filepath.Join(root, "releases", "r819", "channel.v2.json")
	if err := run(bundle, "desktop-client", "windows-amd64", "r819", "0.1.15.819", "alpha-key", "",
		releaseRoot, channel, "", 819, 1); err != nil {
		t.Fatalf("first run: %v", err)
	}
	err := run(bundle, "desktop-client", "windows-amd64", "r819", "0.1.15.819", "alpha-key", "",
		releaseRoot, channel, "", 819, 1)
	if err == nil || !strings.Contains(err.Error(), "refusing to overwrite") {
		t.Fatalf("second run = %v; a release must not be rewritten", err)
	}
}
