[repo]
url=svn://cloud.atmprojekt.pl/FILEES-BIN
channel=stable
platform=openbsd-amd64
svn=/usr/local/bin/svn

[local]
state_dir=/var/filees/install-state
stage_dir=/var/filees/install-stage
backup_dir=/var/filees/install-backup
lock_path=/var/run/filees-install.lock

[install]
sbin_dir=/usr/local/sbin
libexec_dir=/usr/local/libexec
sysconf_dir=/etc/filees
sshd_conf_dir=/etc/ssh/sshd_config.d
ssh_keys_dir=/etc/ssh
login_conf_dir=/etc/login.conf.d
data_dir=/var/filees

[security]
signify=/usr/bin/signify

[policy]
default_action=check
config_drift=block
orphan_files=keep
interactive=true
require_hash=true
verify_signature=true
talkative=false
