package androidbind

import (
	"encoding/json"
	"errors"
	"io"
	"net"
	"strings"
	"sync"
	"testing"

	"golang.org/x/crypto/ssh"
)

// fakePairingServer stands in for the real sshd + forced-command chain
// (internal/servertool/entry.go / mobile_entry.go / mobile_worker.go) that
// pkg/mobileclient/onboard drives - just enough of the wire shape to
// exercise Pair's full push -> prove -> finish sequence, including that the
// SAME identity generated by loadOrCreateIdentity is what gets proved and
// finished. The wire types here deliberately mirror (not import - they are
// unexported in pkg/mobileclient/onboard) internal/servertool/mobile_worker.go's
// MobileOnboardPushPayload/mobileWorkerResult JSON shapes.
type fakePairingServer struct {
	hostSigner ssh.Signer
	wantToken  string

	mu           sync.Mutex
	pushedKey    string
	provenKey    ssh.PublicKey
	seenCommands []string
}

func (f *fakePairingServer) commands() []string {
	f.mu.Lock()
	defer f.mu.Unlock()
	return append([]string(nil), f.seenCommands...)
}

func (f *fakePairingServer) lastPushedKey() string {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.pushedKey
}

type wirePushPayload struct {
	PublicKey   string `json:"public_key"`
	Fingerprint string `json:"fingerprint"`
}

type wireResult struct {
	Schema          string `json:"schema"`
	Status          string `json:"status"`
	OperationID     string `json:"operation_id,omitempty"`
	ClientID        string `json:"client_id,omitempty"`
	ServiceRevision int64  `json:"service_revision,omitempty"`
}

func startFakePairingServer(t *testing.T, f *fakePairingServer) string {
	t.Helper()
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { listener.Close() })

	config := &ssh.ServerConfig{
		PublicKeyCallback: func(_ ssh.ConnMetadata, key ssh.PublicKey) (*ssh.Permissions, error) {
			f.mu.Lock()
			defer f.mu.Unlock()
			if f.provenKey == nil {
				return nil, errors.New("fake pairing server: no key staged yet")
			}
			if key.Type() != f.provenKey.Type() || string(key.Marshal()) != string(f.provenKey.Marshal()) {
				return nil, errors.New("fake pairing server: unexpected installation key")
			}
			return &ssh.Permissions{}, nil
		},
		KeyboardInteractiveCallback: func(_ ssh.ConnMetadata, client ssh.KeyboardInteractiveChallenge) (*ssh.Permissions, error) {
			answers, err := client("", "", []string{"response"}, []bool{false})
			if err != nil {
				return nil, err
			}
			if len(answers) != 1 || answers[0] != f.wantToken {
				return nil, errors.New("fake pairing server: wrong token")
			}
			return &ssh.Permissions{}, nil
		},
	}
	config.AddHostKey(f.hostSigner)

	go func() {
		for {
			conn, err := listener.Accept()
			if err != nil {
				return
			}
			go func() {
				defer conn.Close()
				_, chans, reqs, err := ssh.NewServerConn(conn, config)
				if err != nil {
					return
				}
				go ssh.DiscardRequests(reqs)
				for newChannel := range chans {
					if newChannel.ChannelType() != "session" {
						newChannel.Reject(ssh.UnknownChannelType, "only session channels")
						continue
					}
					channel, requests, err := newChannel.Accept()
					if err != nil {
						continue
					}
					go f.serveOneExec(channel, requests)
				}
			}()
		}
	}()
	return listener.Addr().String()
}

func (f *fakePairingServer) serveOneExec(channel ssh.Channel, requests <-chan *ssh.Request) {
	defer channel.Close()
	for req := range requests {
		if req.Type != "exec" {
			req.Reply(false, nil)
			continue
		}
		var payload struct{ Command string }
		ssh.Unmarshal(req.Payload, &payload)
		req.Reply(true, nil)

		f.mu.Lock()
		f.seenCommands = append(f.seenCommands, payload.Command)
		f.mu.Unlock()

		status := uint32(0)
		var result wireResult
		switch payload.Command {
		case "filees mobile-onboard-v1":
			stdin, _ := io.ReadAll(channel)
			var push wirePushPayload
			if err := json.Unmarshal(stdin, &push); err != nil {
				status = 1
				break
			}
			key, _, _, _, err := ssh.ParseAuthorizedKey([]byte(push.PublicKey))
			if err != nil {
				status = 1
				break
			}
			f.mu.Lock()
			f.pushedKey = push.PublicKey
			f.provenKey = key
			f.mu.Unlock()
			result = wireResult{Status: "staged", OperationID: "op-1", ClientID: "client-1"}
		case "filees-mobile-proof/v1":
			result = wireResult{Status: "proved", OperationID: "op-1", ClientID: "client-1"}
		case "filees-mobile-finish/v1":
			result = wireResult{Status: "active", OperationID: "op-1", ClientID: "client-1", ServiceRevision: 9}
		default:
			status = 1
		}
		if status == 0 {
			if err := json.NewEncoder(channel).Encode(result); err != nil {
				status = 1
			}
		}
		channel.SendRequest("exit-status", false, ssh.Marshal(struct{ Status uint32 }{status}))
		return
	}
}

func TestPairDrivesPushProveFinishWithThePersistedIdentity(t *testing.T) {
	hostSigner := generateEd25519(t)
	f := &fakePairingServer{hostSigner: hostSigner, wantToken: "ABCDEFGH-IJKLMNOPQRSTUVWX"}
	addr := startFakePairingServer(t, f)
	hostKeyLine := string(ssh.MarshalAuthorizedKey(hostSigner.PublicKey()))

	storeDir := t.TempDir()
	resultJSON, err := PairJSON(storeDir, addr, hostKeyLine, f.wantToken)
	if err != nil {
		t.Fatal(err)
	}
	var result PairResult
	if err := json.Unmarshal([]byte(resultJSON), &result); err != nil {
		t.Fatal(err)
	}
	if result.ClientID != "client-1" || result.ServiceRevision != 9 {
		t.Fatalf("result=%+v raw=%s", result, resultJSON)
	}
	want := []string{"filees mobile-onboard-v1", "filees-mobile-proof/v1", "filees-mobile-finish/v1"}
	if got := f.commands(); !equalStrings(got, want) {
		t.Fatalf("server saw commands=%v, want %v", got, want)
	}

	// The pushed key must be the SAME identity NewClient would later use for
	// this exact storeDir - proving Pair reuses loadOrCreateIdentity rather
	// than generating a throwaway key of its own.
	ident, err := loadOrCreateIdentity(storeDir)
	if err != nil {
		t.Fatal(err)
	}
	wantBareKey := strings.TrimSpace(string(ssh.MarshalAuthorizedKey(ident.signer.PublicKey())))
	if f.lastPushedKey() != wantBareKey {
		t.Fatalf("pushed key=%q, want %q", f.lastPushedKey(), wantBareKey)
	}
}

func TestPairRejectsWrongToken(t *testing.T) {
	hostSigner := generateEd25519(t)
	f := &fakePairingServer{hostSigner: hostSigner, wantToken: "ABCDEFGH-IJKLMNOPQRSTUVWX"}
	addr := startFakePairingServer(t, f)
	hostKeyLine := string(ssh.MarshalAuthorizedKey(hostSigner.PublicKey()))

	if _, err := PairJSON(t.TempDir(), addr, hostKeyLine, "WRONGTOK-ENXXXXXXXXXXXXXXX"); err == nil {
		t.Fatal("wrong token accepted")
	}
}

func TestPairRejectsEmptyStoreDir(t *testing.T) {
	if _, err := PairJSON("", "127.0.0.1:1", "ssh-ed25519 AAAA", "token"); err == nil {
		t.Fatal("empty store_dir accepted")
	}
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
